apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  dbpassword: "<path:essential-services/data/autosetup#dbpassword>"
  dbuser: "<path:essential-services/data/autosetup#dbuser>"
  dbUrl: "<path:essential-services/data/autosetup#dbUrl>"