apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autosetup.fullname" . }}
  labels:
    {{- include "autosetup.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "autosetup.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}          
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "autosetup.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.portContainer }}
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: dbuser
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: dbpassword
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: dbUrl
            #- name: SPRING_DATASOURCE_URL
            #  value: "jdbc:postgresql://orch-postgresdb-postgresql:5432/orchdb"
            - name: SPRING_JPA_HIBERNATE_DDL-AUTO
              value: "update"
            - name: VAULT_URL
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: vaultUrl
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: vaultToken
            - name: VAULT_TIMEOUT
              value: "30"
            - name: DAPSWRAPPER_DAPS_TOKEN_URL
              valueFrom:
                secretKeyRef:
                  name: daps-secrets
                  key: dapsTokenUrl
            - name: DAPSWRAPPER_DAPS_JSKURL
              valueFrom:
                secretKeyRef:
                  name: daps-secrets
                  key: dapsJksUrl
            - name: DAPSWRAPPER_DAPS_URL
              valueFrom:
                secretKeyRef:
                  name: daps-secrets
                  key: dapsUrl
            - name: DAPSWRAPPER_KEYCLOAK_TOKENURI
              valueFrom:
                secretKeyRef:
                  name: daps-secrets
                  key: dapswrapperkeycloaktokenURI  
            - name: DAPSWRAPPER_KEYCLOAK_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: daps-secrets
                  key: dapswrapperkeycloakclientId
            - name: DAPSWRAPPER_KEYCLOAK_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: daps-secrets
                  key: dapswrapperkeycloakclientSecret 
            - name: DAPSWRAPPER_URL
              valueFrom:
                secretKeyRef:
                  name: daps-secrets
                  key: dapswrapperUrl 
            - name: KUBEAPP_URL
              valueFrom:
                secretKeyRef:
                  name: kubeapps-secrets
                  key: kubeappsUrl
            - name: KUBEAPP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kubeapps-secrets
                  key: kubeappsToken

            - name: TARGET_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: targetNamesapce
            - name: TARGET_CLUSTER
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: targetCluster
            - name: DNS_NAME_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: dnsnameProtocol
            - name: DNS_NAME
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: dnsname

            #- name: TARGET_NAMESPACE
            #  value: "kubeapps"
            #- name: TARGET_CLUSTER
            #  value: "default"
            #- name: DNS_NAME_PROTOCOL
            #  value: "https"
            #- name: DNS_NAME
            #  value: "tenantname.cx.dih-cloud.com"
            - name: RETRY_MAXATTEMPTS
              value: "3"
            - name: RETRY_BACKOFFDELAY
              value: "500"
            - name: PORTAL_EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: portal-secrets
                  key: portalemail
            - name: PORTAL_URL
              valueFrom:
                secretKeyRef:
                  name: portal-secrets
                  key: portalurl
            - name: PORTAL_KEYCLOAK_TOKENURI
              valueFrom:
                secretKeyRef:
                  name: portal-secrets
                  key: portaltokenurl
            - name: PORTAL_KEYCLOAK_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: portal-secrets
                  key: portalclientid
            - name: PORTAL_KEYCLOAK_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: portal-secrets
                  key: portalclientsecret
            - name: PORTAL_DFT_KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: portal-secrets
                  key: portaldftkeycloakrealm
            - name: PORTAL_DFT_KEYCLOAK_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: portal-secrets
                  key: portaldftkeycloakclient
            - name: PORTAL_DFT_KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: portal-secrets
                  key: portaldftkeyclockurl
            - name: PORTAL_DFT_DIGITALTWINURL
              valueFrom:
                secretKeyRef:
                  name: portal-secrets
                  key: portaldftdigitaltwinurl
            - name: PORTAL_DFT_DIGITALTWINAUTHURL
              valueFrom:
                secretKeyRef:
                  name: portal-secrets
                  key: portaldftdigitaltwinauth               
            - name: KEYCLOAK_REALM
              valueFrom: 
                secretKeyRef:
                  name: keycloack-secrets
                  key: keycloakRealm
            - name: KEYCLOAK_AUTH-SERVER-URL
              valueFrom: 
                secretKeyRef:
                  name: keycloack-secrets
                  key: keycloakAuthserverUrl
            - name: KEYCLOAK_RESOURCES
              valueFrom: 
                secretKeyRef:
                  name: keycloack-secrets
                  key: keycloakResource
            - name: KEYCLOAK_SSL-REQUIRED
              valueFrom: 
                secretKeyRef:
                  name: keycloack-secrets
                  key: keycloakSslRequired
            - name: KEYCLOAK_USE-RESOURCE-ROLE-MAPPINGS
              valueFrom: 
                secretKeyRef:
                  name: keycloack-secrets
                  key: keycloakUseResourceRoleMappings
            - name: KEYCLOAK_BEARER-TOKEN
              valueFrom: 
                secretKeyRef:
                  name: keycloack-secrets
                  key: keycloakBearerOnly
            - name: MANUAL_UPDATE
              valueFrom: 
                secretKeyRef:
                  name: keycloack-secrets
                  key: manualupdate
            - name: MAIL_SMTP_HOST
              valueFrom: 
                secretKeyRef:
                  name: mail-secrets
                  key: smtp_host
            - name: MAIL_SMTP_PORT
              valueFrom: 
                secretKeyRef:
                  name: mail-secrets
                  key: smtp_port
            - name: MAIL_FROM_ADDRESS
              valueFrom: 
                secretKeyRef:
                  name: mail-secrets
                  key: mail_from
            - name: MAIL_REPLYTO_ADDRESS
              valueFrom: 
                secretKeyRef:
                  name: mail-secrets
                  key: mail_to
            - name: MAIL_SMTP_STARTTLS_ENABLE
              valueFrom: 
                secretKeyRef:
                  name: mail-secrets
                  key: smtp_tls_enable
            - name: MAIL_SMTP_AUTH
              valueFrom: 
                secretKeyRef:
                  name: mail-secrets
                  key: smtp_auth             
            #- name: MAIL_SMTP_HOST
            #  value: "mailauth.telekom.de"
            #- name: MAIL_SMTP_PORT
            #  value: "587"
            #- name: MAIL_FROM_ADDRESS
            #  value: "Auto Setup technical team<tech@telekom.de>"
            #- name: MAIL_REPLYTO_ADDRESS
            #  value: "sachin.argade@t-systems.com,ADITYA.GAJBHIYE@t-systems.com"
            #- name: MAIL_SMTP_STARTTLS_ENABLE
            #  value: "true"
            #- name: MAIL_SMTP_AUTH
            #  value: "true"


          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
