apiVersion: v1
kind: Secret
metadata:
  name: keycloack-secrets
type: Opaque
stringData:
  keycloakAuthserverUrl: "<path:essential-services/data/autosetup#keycloakAuthserverUrl>"
  keycloakBearerOnly: "<path:essential-services/data/autosetup#keycloakBearerOnly>"
  keycloakRealm: "<path:essential-services/data/autosetup#keycloakRealm>"
  keycloakResource: "<path:essential-services/data/autosetup#keycloakResource>"
  keycloakSslRequired: "<path:essential-services/data/autosetup#keycloakSslRequired>"
  keycloakUseResourceRoleMappings: "<path:essential-services/data/autosetup#keycloakUseResourceRoleMappings>"
  manualupdate: "<path:essential-services/data/autosetup#manualupdate>"

