apiVersion: v1
kind: Secret
metadata:
  name: vault-secrets
type: Opaque
stringData:
  vaultToken: "<path:essential-services/data/autosetup#vaultToken>"
  vaultUrl: "<path:essential-services/data/autosetup#vaultUrl>"
